import React from "react";
import Image from "next/image";
import clsx from "clsx";

// generated by scripts/generate-image-manifest.mjs
import manifest from "../_data/generated/image-manifest.json";

/**
 * Default sizes per usage context.
 * Override with `sizes` prop when needed.
 */
const SIZES_BY_VARIANT = {
  gallery: "(max-width: 640px) 100vw, (max-width: 1024px) 50vw, 33vw",
  card: "(max-width: 1024px) 100vw, 33vw",
  hero: "100vw",
  reel: "100vw",
  default: "100vw"
};

function normalizeSrc(src) {
  if (!src) return "";
  // Ensure it matches manifest keys ("/images/...")
  if (src.startsWith("http")) return src; // not supported by manifest, but allow
  return src.startsWith("/") ? src : `/${src}`;
}

export default function FCImage({
  src,
  alt,

  variant = "default",
  className,
  imgClassName,

  // next/image sizing
  width: widthProp,
  height: heightProp,
  fill = false,
  sizes: sizesProp,

  // placeholder behavior
  blur = true,

  // perf knobs
  priority = false,
  quality = 75,

  // styling
  objectFit = "cover",
  objectPosition = "center",

  ...rest
}) {
  const normalizedSrc = normalizeSrc(src);

  // Pull details from manifest if available
  const meta = manifest?.[normalizedSrc];

  const width = widthProp ?? meta?.width ?? undefined;
  const height = heightProp ?? meta?.height ?? undefined;

  // For next/image blur placeholder, must be a data URL
  const blurDataURL = meta?.blurDataURL;

  const sizes =
    sizesProp || SIZES_BY_VARIANT[variant] || SIZES_BY_VARIANT.default;

  /**
   * next/image rules:
   * - If fill=true: you must render inside a position:relative container with size
   * - If fill=false: you should provide width+height (we do via manifest)
   */
  const canUseBlur = blur && !!blurDataURL;

  return (
    <span
      className={clsx(
        "relative block overflow-hidden",
        // If not using fill, ensure layout stability even if meta missing
        !fill && !widthProp && !heightProp && !meta?.width
          ? "bg-black/5"
          : null,
        className
      )}
      style={
        fill
          ? undefined
          : width && height
            ? { aspectRatio: `${width} / ${height}` }
            : undefined
      }
    >
      <Image
        src={normalizedSrc}
        alt={alt}
        fill={!!fill}
        width={fill ? undefined : width}
        height={fill ? undefined : height}
        sizes={sizes}
        quality={quality}
        priority={priority}
        placeholder={canUseBlur ? "blur" : "empty"}
        blurDataURL={canUseBlur ? blurDataURL : undefined}
        className={clsx("block", imgClassName)}
        style={{ objectFit, objectPosition }}
        {...rest}
      />
    </span>
  );
}
